# Generated by Django 4.1.3 on 2022-12-26 20:55

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0002_alter_post_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='img',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255),
        ),
    ]
